In [3]:
import numpy as np

In [4]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [6]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [8]:
type(array1)

numpy.ndarray

In [10]:
array1.shape

(11,)

In [14]:
array2 = np.array([[2,3,5],[7,11,13],[17,19,23],[21,29,31]])

In [15]:
array2.shape

(4, 3)

### array2.shape은 (4,3)이 나와..  
4행3열

In [17]:
array1.size

11

In [18]:
array2.size

12

In [22]:
arr=np.arange(1,10)

In [ ]:
arr

### index 

In [4]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [5]:
array1[0]

2

In [6]:
array1[2]

5

In [8]:
array1[-1]

31

In [ ]:
array1[-2]

In [10]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [14]:
array2=np.array([2,1,3])

In [13]:
array1[array2]

array([5, 3, 7])

### slicing

In [15]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [17]:
array1[0:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [18]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [19]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [20]:
#2부터 11까지 1씩 건너뜀
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [21]:
#2부터 11열까지 2씩 건ㄴ너뜀
array1[2:11:3]

array([ 5, 13, 23])

### Numpy 기본연산

In [23]:
array1=np.arange(10)
array2=np.arange(10,20)

In [24]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

각 원소에 2를 곱하자 !

In [26]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
array1 /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
array1 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [30]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

처음에 한 계산은 저장이 안되어있으니 변수에 할당해야 저장댐

In [32]:
#열끼리 더하기
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [41]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
temp = np.array(revenue_in_yen)
temp=temp*10.08
# 정답 출력


In [ ]:
temp

In [44]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
temp_yen= np.array(revenue_in_yen)*10.08
temp_bucks=np.array(revenue_in_dollar)*1138
won_array = temp_yen + temp_bucks
# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### boolean

In [45]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [46]:
array1 > 10

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [47]:
array1 %2 ==0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [48]:
booleans = np.array([True,True,False,True,True,False,True,True,True,False,True])

In [49]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int32),)

In [50]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
np.where(array1>4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32),)

In [52]:
filter = np.where(array1>4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32),)

In [54]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

numpy array를 쓰는 이유 ??
1. 문법차이(길이가 같은 두 배열을 더할 때)
 덧셈 뺄셈 나눗셈할때
2. 성능차이(속도의 차이)


In [56]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [ ]:
print(array1.max())
print(array1.min())

In [58]:
print(array1.mean())

15.25


In [59]:
print(np.median(array1))

13.5


In [60]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875


31
5
